(in-package :pconch)
(defparameter *base* "https://beatworm.co.uk/")
(defparameter *prefix* "/blog/")
(defparameter *port* 2125)
(defparameter *source-dir* "~/Documents/blog/")
(defparameter *www-dir* "~/Sites/blog/")
(defparameter *source-dir* #p"~/Documents/blog/")
(defparameter *template-dir* #p "./templates/")
(defparameter *www-dir* #p"~/Sites/blog/")
(defparameter *cache-dir* (cl-fad:merge-pathnames-as-directory *www-dir* #p".cache/"))
(defparameter *index-cache* (make-instance 'clache:file-store :directory *cache-dir*))
(defparameter *index-pager* 20)
(defvar *last-request* nil)
(defvar *script-name* nil)
;; local overrides can go in here, for site configuration
(load "local.lisp" :if-does-not-exist nil)
