(in-package :pconch)
(defparameter *base* "http://localhost:2125/")
(defparameter *prefix* "/blog/")
(defparameter *port* 2125)
(defparameter *source-dir* "~/Documents/blog/")
(defparameter *www-dir* "~/Sites/blog/")
(defparameter *source-dir* #p"~/Documents/blog/")
(defparameter *template-dir* #p "./templates/")
(defparameter *www-dir* #p"~/Sites/blog/")
(defparameter *index-pager* 20)
(defvar *last-request* nil)
(defvar *script-name* nil)
