Document: pconch
Title: Debian pconch Manual
Author: <insert document author here>
Abstract: This manual describes what pconch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pconch/pconch.sgml.gz

Format: postscript
Files: /usr/share/doc/pconch/pconch.ps.gz

Format: text
Files: /usr/share/doc/pconch/pconch.text.gz

Format: HTML
Index: /usr/share/doc/pconch/html/index.html
Files: /usr/share/doc/pconch/html/*.html
